# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Arcturus122.github.io/dataoil/"

git_url = "https://github.com/Arcturus122/dataoil/tree/master/"

def custom_doc_links(name): return None
