# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Api": "api.ipynb",
         "series": "api.ipynb",
         "plot1": "plot.ipynb",
         "plotN": "plot.ipynb",
         "distplot": "plot.ipynb"}

modules = ["api.py",
           "plot.py"]

doc_url = "https://Arcturus122.github.io/dataoil/"

git_url = "https://github.com/Arcturus122/dataoil/tree/master/"

def custom_doc_links(name): return None
